//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityWeb.Resources.Security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Add {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Add() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnityWeb.Resources.Security.Add", typeof(Add).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 1.
        /// </summary>
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 10.
        /// </summary>
        public static string Question10 {
            get {
                return ResourceManager.GetString("Question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 2.
        /// </summary>
        public static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 3.
        /// </summary>
        public static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 4.
        /// </summary>
        public static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 5.
        /// </summary>
        public static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 6.
        /// </summary>
        public static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 7.
        /// </summary>
        public static string Question7 {
            get {
                return ResourceManager.GetString("Question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 8.
        /// </summary>
        public static string Question8 {
            get {
                return ResourceManager.GetString("Question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 9.
        /// </summary>
        public static string Question9 {
            get {
                return ResourceManager.GetString("Question9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Security Answers.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
