//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityWeb.Resources.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnityWeb.Resources.Dashboard.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENTS AWAITING APPROVAL.
        /// </summary>
        public static string DocumentsAwaitingApproval {
            get {
                return ResourceManager.GetString("DocumentsAwaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIRING APPROVAL.
        /// </summary>
        public static string GridsAwaiitngApproval {
            get {
                return ResourceManager.GetString("GridsAwaiitngApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWAITING HOUSEHOLDING.
        /// </summary>
        public static string GridsAwaiitngHouseHolding {
            get {
                return ResourceManager.GetString("GridsAwaiitngHouseHolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENTLY HOUSEHELD.
        /// </summary>
        public static string GridsRecentylyHouseHeld {
            get {
                return ResourceManager.GetString("GridsRecentylyHouseHeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REJECTED.
        /// </summary>
        public static string GridsRejected {
            get {
                return ResourceManager.GetString("GridsRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILTER BY MANAGEMENT COMPANY:.
        /// </summary>
        public static string ManCoFilter {
            get {
                return ResourceManager.GetString("ManCoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSING NOW.
        /// </summary>
        public static string ProcessingNow {
            get {
                return ResourceManager.GetString("ProcessingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTIONS.
        /// </summary>
        public static string RecentExceptions {
            get {
                return ResourceManager.GetString("RecentExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSING COMPLETE.
        /// </summary>
        public static string RecentlyCompleted {
            get {
                return ResourceManager.GetString("RecentlyCompleted", resourceCulture);
            }
        }
    }
}
