//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityWeb.Resources.Document {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Search {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Search() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnityWeb.Resources.Document.Search", typeof(Search).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GRID to Basket.
        /// </summary>
        public static string AddGridToBasket {
            get {
                return ResourceManager.GetString("AddGridToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addressee Sub Type.
        /// </summary>
        public static string AddresseeSubType {
            get {
                return ResourceManager.GetString("AddresseeSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Basket.
        /// </summary>
        public static string AddToBasket {
            get {
                return ResourceManager.GetString("AddToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ApprovalStatus {
            get {
                return ResourceManager.GetString("ApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Selected Documents.
        /// </summary>
        public static string ApproveDocument {
            get {
                return ResourceManager.GetString("ApproveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve GRID.
        /// </summary>
        public static string ApproveGrid {
            get {
                return ResourceManager.GetString("ApproveGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to approve this GRID. Are you sure that you want to continue?.
        /// </summary>
        public static string ApproveGridMsg {
            get {
                return ResourceManager.GetString("ApproveGridMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA LEVEL.
        /// </summary>
        public static string DataLevel {
            get {
                return ResourceManager.GetString("DataLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Documents Approved =.
        /// </summary>
        public static string DocsApproved {
            get {
                return ResourceManager.GetString("DocsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Documents Awaiting Approval =.
        /// </summary>
        public static string DocsAwaitingApproval {
            get {
                return ResourceManager.GetString("DocsAwaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Sub Type.
        /// </summary>
        public static string DocSubType {
            get {
                return ResourceManager.GetString("DocSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Type.
        /// </summary>
        public static string DocType {
            get {
                return ResourceManager.GetString("DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Id.
        /// </summary>
        public static string DocumentId {
            get {
                return ResourceManager.GetString("DocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENT LEVEL.
        /// </summary>
        public static string DocumentLevel {
            get {
                return ResourceManager.GetString("DocumentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Documents in GRID =.
        /// </summary>
        public static string DocumentsInGrid {
            get {
                return ResourceManager.GetString("DocumentsInGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRID LEVEL.
        /// </summary>
        public static string GridLevel {
            get {
                return ResourceManager.GetString("GridLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investor Reference.
        /// </summary>
        public static string InvestorReference {
            get {
                return ResourceManager.GetString("InvestorReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Print Flag.
        /// </summary>
        public static string MailPrintFlag {
            get {
                return ResourceManager.GetString("MailPrintFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Company.
        /// </summary>
        public static string ManCo {
            get {
                return ResourceManager.GetString("ManCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject GRID.
        /// </summary>
        public static string RejectGrid {
            get {
                return ResourceManager.GetString("RejectGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to reject this GRID. Are you sure that you want to continue?.
        /// </summary>
        public static string RejectGridMsg {
            get {
                return ResourceManager.GetString("RejectGridMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing documents .
        /// </summary>
        public static string ShowingDocuments {
            get {
                return ResourceManager.GetString("ShowingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Level Search.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of documents.
        /// </summary>
        public static string TotalItems {
            get {
                return ResourceManager.GetString("TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
