//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityWeb.Resources.CartItems {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnityWeb.Resources.CartItems.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ApprovalStatus {
            get {
                return ResourceManager.GetString("ApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve all Documents in Basket.
        /// </summary>
        public static string ApproveBasket {
            get {
                return ResourceManager.GetString("ApproveBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to approve all documents in your basket. Are you sure that you want to continue?.
        /// </summary>
        public static string ApproveBasketConfirm {
            get {
                return ResourceManager.GetString("ApproveBasketConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Selected Documents.
        /// </summary>
        public static string ApproveDocument {
            get {
                return ResourceManager.GetString("ApproveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket Items.
        /// </summary>
        public static string CartItems {
            get {
                return ResourceManager.GetString("CartItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Sub Type.
        /// </summary>
        public static string DocSubType {
            get {
                return ResourceManager.GetString("DocSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Type.
        /// </summary>
        public static string DocType {
            get {
                return ResourceManager.GetString("DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty basket.
        /// </summary>
        public static string EmptyBasket {
            get {
                return ResourceManager.GetString("EmptyBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all Documents in Basket.
        /// </summary>
        public static string ExportBasket {
            get {
                return ResourceManager.GetString("ExportBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Selected Documents.
        /// </summary>
        public static string ExportDocument {
            get {
                return ResourceManager.GetString("ExportDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Company.
        /// </summary>
        public static string ManCo {
            get {
                return ResourceManager.GetString("ManCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to rejected all documents in your basket. Are you sure that you want to continue?.
        /// </summary>
        public static string RejectBasketConfirm {
            get {
                return ResourceManager.GetString("RejectBasketConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Selected Documents.
        /// </summary>
        public static string RejectDocument {
            get {
                return ResourceManager.GetString("RejectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject all Documents in Basket.
        /// </summary>
        public static string RejectGrid {
            get {
                return ResourceManager.GetString("RejectGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected item from Basket.
        /// </summary>
        public static string RemoveFromCart {
            get {
                return ResourceManager.GetString("RemoveFromCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing Documents.
        /// </summary>
        public static string ShowingDocuments {
            get {
                return ResourceManager.GetString("ShowingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number Of Documents.
        /// </summary>
        public static string TotalItems {
            get {
                return ResourceManager.GetString("TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Basket.
        /// </summary>
        public static string YourCart {
            get {
                return ResourceManager.GetString("YourCart", resourceCulture);
            }
        }
    }
}
